[project]
name="NUCS"
version="0.7.0"
authors = [
  { name="Yan Georget", email="yan.georget@gmail.com" },
]
description="A Numpy and Numba based Python library for solving Constraint Satisfaction Problems"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "numba==0.60.0",
    "numpy==2.0.1",
]
[project.urls]
Homepage = "https://github.com/yangeorget/nucs"
Issues = "https://github.com/yangeorget/nucs"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120

[tool.setuptools.packages]
find = {}